config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :walkers
  resources :owners
  resources :dogs

  get "/search" => "search#index"
  get "/search/results" => "search#results"

  get "/owners/profile" => "owners#show"
  post "/owners/profile" => "owners#edit"

  get "/walkers/profile" => "walkers#show"
  post "/walkers/profile" => "walkers#edit"

  get "/session/new" => "session#new"
  post "/session" => "session#create"
  get "/logout" => "session#destroy"

end

app/models/dog.rb
# == Schema Information
#
# Table name: dogs
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  name        :string(255)
#  age         :integer
#  sex_id      :integer
#  breed_id    :integer
#  size_id     :integer
#  temperment  :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Dog < ActiveRecord::Base
  belongs_to :user

  # TODO Figure out Dog Model relationships
  # ideally, a dog will belong to a WALKER through
  # an OWNER.  Having the WALKER/OWNER status
  # set by a boolean upon account creation, we will
  # have to set the relationship based on that
  # boolean value

  has_one :sex
  has_one :size
  has_one :breed


end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  # the NEW method loads all the required data
  # from the database and stores them in to the
  # instance variables SEXES, SIZES, BREEDS that
  # are used on the add a dog menu
  def new
    @dog = Dog.new
    @sexes = Sex.all
    @sizes = Size.all
    @breeds = Breed.all
  end

  def create
    @dog= Dog.new(dog_params)
    if @dog.save
      redirect_to("/")
    else
      render :new
    end
  end

  def show
    @dog = Dog.find_by(id: params[:id])
  end

  def edit
    @dog = Dog.find_by(id: params[:id])
    @sexes = Sex.all
    @sizes = Size.all
    @breeds = Breed.all
  end

  def update
    @dog = Dog.find_by(id: params[:id])

    if @dog.update(dog_params)
      redirect_to @dog
    else
      render :edit
    end
  end

  def destroy
    @dog = Dog.find_by(id: params[:id])
    @dog.delete
    redirect_to("/")
  end

  private

  def dog_params
    params.require(:dog).permit(
      :name,
      :age,
      :sex_id,
      :breed_id,
      :size_id,
      :temperment,
      :description,
      :user_id)
  end

end

app/views/dogs/edit.html.erb
<%= form_for(@dog) do |f| %>
  <%= f.label(:name) %>
  <%= f.text_field(:name) %>
  <%= f.label(:age) %>
  <%= f.number_field(:age) %>
  <%= f.label(:sex_id) %>
  <%= f.collection_select(:sex_id, @sexes, :id, :sex) %>
  <%= f.label(:breed_id) %>
  <%= f.collection_select(:breed_id, @breeds, :id, :name) %>
  <%= f.label(:size_id) %>
  <%= f.collection_select(:size_id, @sizes, :id, :name) %>
  <%= f.label(:temperment) %>
  <%= f.text_field(:temperment) %>
  <%= f.label(:description) %>
  <%= f.text_area(:description) %>
  <%= f.hidden_field(:user_id, :value => current_owner.id) %>
  <%= f.submit %>
<% end %>

app/views/dogs/new.html.erb
<h1>Please create a new dog</h1>

<%= form_for(@dog) do |f| %>
  <%= f.label(:name) %>
  <%= f.text_field(:name) %>
  <%= f.label(:age) %>
  <%= f.number_field(:age) %>
  <%= f.label(:sex_id) %>
  <%= f.collection_select(:sex_id, @sexes, :id, :sex) %>
  <%= f.label(:breed_id) %>
  <%= f.collection_select(:breed_id, @breeds, :id, :name) %>
  <%= f.label(:size_id) %>
  <%= f.collection_select(:size_id, @sizes, :id, :name) %>
  <%= f.label(:temperment) %>
  <%= f.text_field(:temperment) %>
  <%= f.label(:description) %>
  <%= f.text_area(:description) %>
  <%= f.hidden_field(:user_id, :value => current_owner.id) %>
  <%= f.submit %>
<% end %>

app/views/dogs/show.html.erb
<h3> <%= @dog.name %> </h3>

<%= button_to "Home", root_path %>
<%= button_to "Edit", edit_dog_path(@dog) %>
<%= form_for(@dog, {:method => :delete}) do |f| %>
<%= f.submit "Remove" %>
<% end %>

<p>Age:  <%= @dog.age %> </p>
<p>Size:  <%= Size.find_by(id: @dog.size_id).name %> </p>
<p>Breed:  <%= Breed.find_by(id: @dog.breed_id).name %> </p>
<p>Temperment:  <%= @dog.temperment %> </p>
<p>Description:  <%= @dog.description %> </p>