config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :walkers
  resources :owners
  resources :dogs

  get "/search" => "search#index"
  get "/search/results" => "search#results"

  get "/owners/profile" => "owners#show"
  post "/owners/profile" => "owners#edit"

  get "/walkers/profile" => "walkers#show"
  post "/walkers/profile" => "walkers#edit"

  get "/session/new" => "session#new"
  post "/session" => "session#create"
  get "/logout" => "session#destroy"

end

app/models/boro.rb
# == Schema Information
#
# Table name: boros
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Boro < ActiveRecord::Base
  has_many :neighborhoods
  has_many :users

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if owner_logged_in?
      @dogs = Dog.where(user_id: current_owner.id)
    end
  end

end

app/views/welcome/_owner_prof_info.html.erb
<ul>
  <h2><small>Name:</small></h2>

  <p>
    <%= current_owner.first_name %> <%= current_owner.last_name %>
  </p>

   <ul class="small-block-grid-3">
    <li><!-- block 1 --></li>
    <li><!-- block 2 --></li>
    <li><img src="<%= current_owner.image_url %>" alt="profile picture" class="profile-pic"></li>
  </ul>

  <h2> <small>Your Boro:</small> </h2>
  <%= current_owner.boro.name %>
  <!-- # OPTIMIZE This neighborhood shit is ugly! -->
    <% if current_owner.owner_profile != nil %>
      <h2> <small>Your Neighborhoods:</small> </h2>
        <p>
          <%= Neighborhood.find_by(id: current_owner.owner_profile.neighborhood_id).name %>
        </p>
      <h2><small>Your Bio: </small></h2>
   <%= current_owner.bio %>

    <% end %>
</ul>

app/views/welcome/_walker_prof_info.html.erb
<ul>
  <h2><small>Name:</small></h2>

  <p>
    <%= current_walker.first_name %> <%= current_walker.last_name %>
  </p>

  <ul class="small-block-grid-3">
    <li><!-- block 1 --></li>
    <li><!-- block 2 --></li>
    <li><img src="<%= current_walker.image_url %>" alt="profile picture"></li>
  </ul>


  <h2> <small>Your Boro:</small> </h2>
  <%= current_walker.boro.name %>

  <% if current_walker.walker_profile != nil %>
  <h2> <small>Your Neighborhoods:</small> </h2
    <!-- this is super weird, the first element in the array when a
    user adds neighborhoods is an empty string, hence the range that eliminates index -->
    <% a = current_walker.walker_profile.neighborhood_ids[1..-1] %>
    <% a.each do |hood| %>
      <p><%= Neighborhood.find_by(id: hood).name %></p>
    <% end %>


 <h2><small>Your Bio: </small></h2>
 <%= current_walker.bio %>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<!-- <div class="small-12 large-6 columns"> -->

  <!-- <div class ="row"> -->

  <!-- </div> -->
  <% if walker_logged_in? %>
    <h4>Dog Walker's Profile</h4>

  <a href="/walkers/profile">Configure Profile</a>

  <%= render 'walker_prof_info' %>

  <% elsif owner_logged_in? %>

  <ul>
    <p>
      <h4>Owner's Profile</h4> <a href="/dogs/new">Add your pup!</a>
    </p>
    <p>
      <a href = "/search">Search for a Walker</a>
    </p>
    <p>
      <a href ="/owners/profile">Configure Your Profile</a>
    </p>
  </ul>

  <%= render 'owner_prof_info' %>



  <ul>
    <h2><small>Your Puppies!</small></h2>
  </ul>
  <ul>
    <% @dogs.each do |dog| %>
      <li><%=link_to(dog.name, controller: :dogs, action: :show, id: dog.id) %></li>
    <% end %>
  </ul>

  <% else %>

  <% end %>
<!-- </div> -->

<div class="fixed">
  <nav class="top-bar" data-topbar>
    <section class="top-bar-section">
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">pupPromenade</a></h1>
      </li>
      </ul>
      <ul class="right">
        <% if walker_logged_in? || owner_logged_in? %>
        <li class="active">
          <a href="logout">Logout</a>
        </li>
        <% else %>

        <li class="has-dropdown">
          <a>Sign Up</a>
          <ul class="dropdown">
            <li>
              <a href="owners/new">as a Dog Owner</a>
            </li>
            <li>
              <a href="walkers/new">as a Dog Walker</a>
            </li>
          </ul>
        </li>
        <li class="active">
          <a href="/session/new">Login</a>
        </li>
      </ul>

    </section>
  </nav>
</div>

<div id="wrapper">
  <div id="title-text">
    <h3 id="welcome-text">Welcome to</h3>
  </div>
  <div id="title-div">
    <h1 id="welcome-title">pupPromenade</h1>
  </div>
  <p id="slogan">Find a walker for your tail-wagger</p>
</div>
<% end %>